### PR TITLE
Replace https URL with https

### PR DESCRIPTION
**Pull request by grappler**
fixes https://github.com/outlandishideas/wpackagist/issues/142

### CODE REVIEW

**Comment by tamlyn** [comment]
Looks good! Will test this and should get it deployed this week.

**Comment by vinkla** [comment]
@grappler great work! Anything we can do to help getting this merged?

**Comment by vinkla** [comment]
@tamlyn :+1:

**Comment by tamlyn** [comment]
That's deployed now. Thanks both.

**Comment by vinkla** [comment]
Seems WordPress SSL certificates isn't the best. Getting this now :cry: Nothing we can do about it though.

> Failed to download wpackagist-plugin/wp-seo-tamer from source: Package could not be downloaded, 
svn: E175002: Unable to connect to a repository at URL 'https://plugins.svn.wordpress.org/wp-seo-tamer/tags/1.3'
svn: E175002: OPTIONS of 'https://plugins.svn.wordpress.org/wp-seo-tamer/tags/1.3': Server certificate verification failed: issuer is not trusted (https://plugins.svn.wordpress.org)

**Comment by grappler** [comment]
@vinkla It worked fine for me. I don't think it is a SSL certificate issue as WP uses the same certificate for all the wp sites. It would be more likely an issue with your server or the network connection.

**Comment by vinkla** [comment]
@grappler did you try running with `--prefer-source`?

**Comment by tamlyn** [comment]
I can confirm using `--prefer-source` results in certificate errors. Weird thing is I can't repro the error if I access the URL using `curl` or `file` in PHP. Is Composer doing some non-default extra SSL checking?

**Comment by grappler** [comment]
Strange because it works for me using `--prefer-source`.

**Comment by tamlyn** [comment]
I'm using PHP 7.0 on OS X 10.10 with latest Composer 1.0-dev.

**Comment by grappler** [comment]
Ah, it seems like a composer issue as the version from 2016-03-11 is working but when I update to the latest is also not working.

**Comment by grappler** [comment]
I updated composer again and was able to download the source without an issue.

**Pull request merged**
