### PR TITLE
Update index.php

### PR DESCRIPTION
**Pull request by iqre8**
Disable debug by default

### CODE REVIEW

**Comment by NoelLH** [comment]
While I think this made sense with the previous libs, it is hopefully unnecessary now with the move to Symfony Flex and related changes.

**Comment by iqre8** [comment]
If it doesn't make sense, shouldn't we then at delete the line?

**Comment by NoelLH** [comment]
@iqre8 the line is already gone, as part of the changes on https://github.com/outlandishideas/wpackagist/pull/314

**Comment by iqre8** [comment]
Thanks for the update.
Will delete this branch then.

**Pull request closed without merging**
