### PR TITLE
Modernize usage of libraries

### PR DESCRIPTION
**Pull request by khromov**
We are starting a WPackagist mirror for our own use and had multiple problems setting up the project after trying to update the dependencies. This patch will correct any currently broken dependencies and update most of them to the latest versions.

Changelog:

* Updated Composer to latest stable
* Updated Doctrine DBAL to 2.5
* Updated Rarst WPOrg client to latest dev-master
* Kept all Symfony/Silex-related stuff at the 2.3 branch
* Added a `run-cron.php` script for easy triggering the update process from a CRON job.

### CODE REVIEW

**Comment by joaquimds** [comment]
Cheers for this (y)

**Comment by joaquimds** [comment]
Let us know if you modernize it further to run on PHP 7...

**Comment by khromov** [comment]
@joaquimds This should run on PHP 7. That's what we are using!

**Comment by joaquimds** [comment]
@khromov Awesome, thanks!

**Pull request merged**
